title: Juan D. Mayor-Nunez
logo: 1710345813282.jpg
description: I’m a Business Technology Management student at Seneca College with a strong interest in data analysis, finance, and technology. Skilled in Python, SQL, and Power BI, I enjoy turning complex data into clear, actionable insights. Originally from Colombia, I bring a global mindset and a strong work ethic to every project I take on.
show_download: True
theme: jekyll-theme-minimal
